cart/urls.py
from django.urls import path
from .views import *


app_name = 'cart'


urlpatterns =[
    path("session/add-product/",SessionAddProduct.as_view(), name = "session-add-product"),
    path("summary/",CartSummaryView.as_view(), name = "cart-summary"),
    path("session/update-product-quantity/",SessionUpdateProductQuantityView.as_view(),name="session-update-product-quantity"),
    path("session/remove-product/",SessionRemoveProductView.as_view(),name="session-remove-product"),


]    

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("root.urls")),
    path("product/",include("product.urls")),
    path("accounts/",include("accounts.urls")),
    path("cart/",include("cart.urls")),
    path("dashboard/",include("dashboard.urls")),
    path("order/",include("order.urls")),
    path("payment/",include("payment.urls")),
    path("review/",include("review.urls")),
    path('api-auth/', include('rest_framework.urls')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from django.urls import path, include
from .views import*

app_name = "order"

urlpatterns = [
    path("checkout/",OrderCheckOutView.as_view(), name="checkout"),
    path("completed/",OrderCompletedView.as_view(),name="completed"),
    path("validate-coupon/",ValidateCouponView.as_view(),name="validate-coupon"),
    path("failed/",OrderFailedView.as_view(),name="failed"),
]

cart/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from accounts.models import CustomeUser
# Create your models here.

class CartModel(models.Model):
    user = models.ForeignKey(CustomeUser, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email
    
    def calculate_total_price(self):
        return sum(item.product.get_price() * item.quantity for item in self.cart_items.all())
    
class CartItemModel(models.Model):
    cart = models.ForeignKey(CartModel, on_delete=models.CASCADE, related_name="cart_items")
    
    # استفاده از ContentType برای نگه داشتن نوع مدل محصول
    product_content_type = models.ForeignKey(ContentType, on_delete=models.PROTECT)
    
    # نگه داشتن ID محصول
    product_object_id = models.PositiveIntegerField()
    
    # ایجاد GenericForeignKey با استفاده از دو فیلد بالا
    product = GenericForeignKey('product_content_type', 'product_object_id')
    
    quantity = models.PositiveIntegerField(default=0)
    
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product.title}-{self.cart.id}"

cart/forms.py
from django import forms
from django.contrib.contenttypes.models import ContentType
from .models import CartItemModel

class CartItemAdminForm(forms.ModelForm):
    product_selector = forms.ChoiceField(label="Product")  # فیلد سفارشی برای نمایش محصولات

    class Meta:
        model = CartItemModel
        fields = ['cart', 'quantity', 'product_selector']  # استفاده از فیلد ترکیب‌شده

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        product_choices = []
        content_types = ContentType.objects.filter(model__in=['clothing', 'dijitalgoods','homeappliances','beauty','appliances','supermarket','child_and_baby'])  # مدل‌های موردنظر
        for ct in content_types:
            model_class = ct.model_class()
            if model_class:
                for product in model_class.objects.all():
                    product_choices.append((f"{ct.pk}-{product.pk}", f"{product.title} ({ct.model})"))

        self.fields['product_selector'].choices = product_choices

    def save(self, commit=True):
        instance = super().save(commit=False)

        # اطمینان از اینکه محصول انتخاب شده
        if 'product_selector' in self.cleaned_data:
            product_data = self.cleaned_data['product_selector'].split('-')
            instance.product_content_type_id = product_data[0]  # شناسه ContentType
            instance.product_object_id = product_data[1]        # شناسه محصول

        if commit:
            instance.save()
        return instance

cart/views.py
from django.views.generic import View,TemplateView
from django.http import JsonResponse
from .cart import CartSession
from typing import Any

# Create your views here.

class SessionAddProduct(View):
    def post(self, request, *args, **kwargs):
        cart = CartSession(request.session)
        product_id = request.POST.get("product_id")
        model_name = request.POST.get("model_name")  # دریافت model_name از درخواست
        quantity = request.POST.get("quantity")

        if product_id and model_name:  # اطمینان از اینکه هر دو موجود باشند
            quantity = int(quantity) if quantity else 1
            cart.add_product(product_id, model_name , quantity)  # ارسال product_id و model_name به متد add_product
        if request.user.is_authenticated:
            cart.merge_session_cart_in_db(request.user)

        return JsonResponse({"cart": cart.get_cart_dict(), "total_quantity": cart.get_total_quantity()})


class CartSummaryView(TemplateView):
    template_name = "cart/cart-summary.html"

    def get_context_data(self, **kwargs: Any):
        context = super().get_context_data(**kwargs)
        cart = CartSession(self.request.session)
        cart_items = cart.get_cart_items()
        context["cart_items"] = cart_items
        context["total_quantity"] = cart.get_total_quantity()
        context["total_payment_price"] = cart.get_total_payment_amount()
        return context

   

class SessionUpdateProductQuantityView(View):

    def post(self, request, *args, **kwargs):
        cart = CartSession(request.session)
        product_id = request.POST.get("product_id")
        quantity = request.POST.get("quantity")
        if product_id and quantity:
            cart.update_product_quantity(product_id, quantity)
        if request.user.is_authenticated:
            cart.merge_session_cart_in_db(request.user)
        return JsonResponse({"cart": cart.get_cart_dict(), "total_quantity": cart.get_total_quantity()})

class SessionRemoveProductView(View):

    def post(self, request, *args, **kwargs):
        cart = CartSession(request.session)
        product_id = request.POST.get("product_id")
        if product_id:
            cart.remove_product(product_id)

        if request.user.is_authenticated:
            cart.merge_session_cart_in_db(request.user)
        return JsonResponse({"cart": cart.get_cart_dict(), "total_quantity": cart.get_total_quantity()})

templates/cart/cart-summary.html
{% extends 'base.html' %}
{% load static %}
{% block 'content' %}
    <!-- OPACITY SCREEN FOR SEARCH INPUT FOCUS -->
    <div class="absolute w-full h-screen bg-gray-200 opacity-40 z-40 hidden" id="opacitiScreen" onclick="closeScreen()">
    </div>
  </div>
  <!-- MAIN -->
  <div class="max-w-[1440px] mx-auto px-3">
    <div class="bg-white shadow-xl my-5 lg:my-10 rounded-xl md:rounded-2xl p-3 md:p-5">
      <div class="relative overflow-x-auto rounded-2xl border">
        <table class="w-full text-sm text-left rtl:text-right text-gray-500">
          <thead class="hidden md:table-header-group text-xs text-gray-700 bg-gray-50">
            <tr>
              <th scope="col" class="px-16 py-3">
                <span class="sr-only">تصویر</span>
              </th>
              <th scope="col" class="md:pr-6 py-3">
                نام محصول
              </th>
              <th scope="col" class="pr-10 py-3">
                تعداد
              </th>
              <th scope="col" class="px-6 py-3">
                قیمت
              </th>
              <th scope="col" class="px-6 py-3">
                دستورات
              </th>
            </tr>
          </thead>
          <tbody class="grid grid-cols-1 sm:grid-cols-2 md:contents gap-5">
            {% for item in cart_items %}
            <tr class="bg-white border-b hover:bg-gray-50 grid grid-cols-1 justify-items-center md:table-row">
              <td class="p-4">
                <img src="{{item.product_obj.image1.url}}" class="w-48 md:w-32 max-w-full max-h-full rounded-lg" alt="">
              </td>
              <td class="md:pr-6 py-4 text-sm opacity-90 text-gray-900">
                {{item.product_obj.title}}
              </td>
              <td class="px-6 py-4">
                <div>
                    <button class="decrement-btn w-8 h-8 rounded-full border text-lg font-semibold focus:outline-none" 
                            onclick="updateQuantity('{{ item.product_obj.id }}', -1)">−</button>
                    <input class="quantity-input w-12 h-8 mx-2 text-center border rounded-lg focus:outline-none" 
                           type="number" 
                           min="1" 
                           max="{{ item.product_obj.stock }}" 
                           value="{{ item.quantity }}" 
                           data-product-id="{{ item.product_obj.id }}"
                           readonly>
                    <button class="increment-btn w-8 h-8 rounded-full border text-lg font-semibold focus:outline-none" 
                            onclick="updateQuantity('{{ item.product_obj.id }}', 1)">+</button>
                </div>
            </td>
              <td class="px-6 py-4 text-sm opacity-90 text-gray-900 formatted-price">
                {{item.total_price}}
              </td>
              <td class="px-6 py-4">
                <button  class=" text-red-600" onclick="removeProduct('{{item.product_id}}')">حذف</button>
              </td>
            </tr>
         {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="border shadow-xl rounded-2xl mx-auto max-w-xl mt-7 flex flex-col gap-y-5 py-5 px-5 md:px-20">
        <div class="flex justify-between">
          <div>
            قیمت کل:
          </div>
          <div class="flex gap-x-1 formatted-price">
            <div>
              {{total_payment_price}}
            </div>
          </div>
        </div>
       
      </div>
      <a href="{% url 'order:checkout' %}" class="flex justify-center items-center opacity-90 my-5">
        <button class="px-7 py-2 text-center text-white bg-red-500 align-middle border-0 rounded-lg shadow-md text-sm">تایید و پرداخت</button>
      </a>
    </div>
  </div>

</body>
  <!--DROPDOWNS FOR NAVBAR-->
  <script src="https://unpkg.com/@themesberg/flowbite@1.1.1/dist/flowbite.bundle.js"></script>
  <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer>
  </script>
  
  <!-- INPUTS ADD NUMBER -->
  <script src="{% static 'assets/js/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script>
    function updateQuantity(product_id, change) {
        const input = document.querySelector(`input[data-product-id="${product_id}"]`);
        let currentQuantity = parseInt(input.value, 10);
        const maxQuantity = parseInt(input.max, 10);
        const newQuantity = currentQuantity + change;

        if (newQuantity >= 1 && newQuantity <= maxQuantity) {
            // به‌روزرسانی مقدار جدید در ورودی
            input.value = newQuantity;

            // فراخوانی ایجکس برای به‌روزرسانی در سرور
            changeProductQuantity(product_id, newQuantity);
        }
    }

    function changeProductQuantity(product_id, quantity) {
      console.log(product_id, quantity);
        $.ajax({
            url: "{% url 'cart:session-update-product-quantity' %}",
            method: 'POST',
            data: {
                product_id: product_id,
                quantity: quantity,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function (response) {
                console.log(response);
                window.location.reload();
                // می‌توانید اینجا بدون بارگذاری مجدد، صفحه را به‌روزرسانی کنید
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log(errorThrown);
            }
        });
    }

  function removeProduct(product_id){
        $.ajax({
            url: "{%  url 'cart:session-remove-product' %}",
            method: 'POST',
            data: {
                product_id: product_id,
                csrfmiddlewaretoken: '{{ csrf_token }}'
    
            },
            success: function (response) {
                console.log(response);
                window.location.reload();
                // do something with the response data
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log(errorThrown);
                // handle the error case
            }
        });
    }
</script>
</html>

{% endblock 'content' %}